name: Build Android APK AAB

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install
        run: npm install

      - name: Build
        run: npm run build

      - name: Capacitor
        run: |
          npm install @capacitor/core
          npm install @capacitor/cli
          npm install @capacitor/android

      - name: Capacitor Init
        run: |
          npx cap init FeiraLivre com.feiralivre.app --web-dir dist

      - name: Android Add
        run: npx cap add android

      - name: Sync
        run: npx cap sync android

      - name: Gradle Permission
        run: chmod +x android/gradlew

      - name: APK
        run: |
          cd android
          ./gradlew assembleDebug

      - name: AAB
        run: |
          cd android
          ./gradlew bundleRelease

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: android/app/build/outputs/apk/debug/app-debug.apk

      - name: Upload AAB
        uses: actions/upload-artifact@v4
        with:
          name: app-release-aab
          path: android/app/build/outputs/bundle/release/app-release.aab
