name: Gerar APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          
      - name: Instalar Dependências
        run: npm install

      - name: Build do Projeto (Vite)
        run: npm run build

      - name: Configurar Android (Capacitor)
        run: |
          npx cap add android
          npx cap sync android

      - name: Gerar APK Final
        run: |
          cd android
          chmod +x gradlew
          ./gradlew assembleDebug

      - name: Disponibilizar Link de Download
        uses: actions/upload-artifact@v4
        with:
          name: aplicativo-calculadora-apk
          path: android/app/build/outputs/apk/debug/app-debug.apk
